#
# cfg/default.toml
#

target_name = "Default"
machine_name = "Generic"

arch="riscv32"
endianness = "little"
abi="ilp32"
fpu="none"
features = ["omit-frame-pointer"]


word_width = 64
size_width = 64
integer_width = 32
float_width = 64
pointer_width = 64
char_width = 8

# decimal floating point compile time precision
precision = 256

libs = [""]

#[backend]
backend = "llvm"

#[backend.llvm]
target_datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"
target_triple = "arm64-apple-macosx12.0.0"

#[backend.c]
int_width = 32
long_width = 64
long_long_width = 64
true_literal = "true"
false_literal = "false"
output_style = "legacy"


public_vars_forbidden = false


