
# default config will be loaded after compiler start
[Default]
char_size = 8
integer_size = 32
pointer_size = 64
float_size = 64
#stdlib_path = ""
backend = "llvm"
target_datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"
target_triple = "arm64-apple-macosx12.0.0"


# Custom config example (redefinition of default values)
# use --setup=CortexM3 compiler flag
[CortexM3]
integer_size = 32
pointer_size = 32
float_size = 32
backend = "llvm"


