cd 0.* && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd 1.* && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd 2.* && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd 3.* && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd 4.* && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd 9.* && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd 10.* && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd 11.* && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd 12.* && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd 14.* && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd var && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd 22.* && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd 23.* && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd cons && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd composite && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd xor && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd named_args && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd let && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd shift && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd string_concat_eq && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd assign_array && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd assign_record && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd assignation && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd va_list && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd char && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd float && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd builtin_constants && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd string && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd crc32 && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd float && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd free_pointer && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd unistd && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd generic && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd print && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd 13.* && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd sizeof && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd memcopy && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd slices && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd default_params && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd queue && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd cmd && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd unicode && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd array && printf "\nBUILD: $PWD\n" && make -j7 test && cd .. && \
cd prefix && printf "\nBUILD: $PWD\n" && make -j7 test && cd ..

